apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: t9-2023630402-web-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: azurefile-csi
